### ISSUE TITLE
EF 9 support

### ISSUE THREAD

**Issue by georg-jung** [artiomchi/FlexLabs.Upsert#172]
Thanks for creating this upsert helper! I use it in multiple projects and think it is a very useful addition.

I'd be interested in a `v9.x` with support for EF 9 to unblock upgrading my project. Let me know if there is a way I could help with that.

It might make sense to also limit the EF dependency to the same major version, as e.g. [Npgsql.EntityFrameworkCore.PostgreSQL](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL#dependencies-body-tab) does:

![Image](https://github.com/user-attachments/assets/2c626bdf-6390-475e-9a20-0263a37356d1)

**Comment by artiomchi** [comment]
Hey @georg-jung! Apologies, for some reason I was sure I already released the v9, but clearly I haven't, life got in the way.

It was a good suggestion to create the version bounds - the .NET project config did not allow me to do that easily in the past, but looks like it's finally working as expected, so in this version I've added the version bounds too! 

Thank you for your patience and support!

**Comment by georg-jung** [comment]
No worries, thanks for getting this done!

Maybe you forgot pushing the relevant commit? Looks like the csproj here in the repo is still at 8.1.2..

**Comment by artiomchi** [comment]
Ahh, I pushed the changes to a .NET 9 feature branch and didn't merge it back to main!

**Comment by georg-jung** [comment]
I see, thanks for fixing!
